sam-per-ref-count: initial commit
maragkakislab/samutils pull request #1
Opened 2020-10-21 19:50 UTC by dar19

2020-10-23 01:09 UTC, mnsmar requested changes
@dar19 please address these comments

2020-10-23 01:09 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser = argparse.ArgumentParser()
Missing description

2020-10-23 01:09 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser.add_argument("-c","--column1", default= "reference", help = "Header of first output column wih reference names, default: reference")
Rename to `--ref-col-name` instead of `--column1`

2020-10-23 01:09 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser.add_argument("-d","--column2", default= "read_count", help = "Header of second output column wih No of counts per reference, default : count")
Rename to `--cnt-col-name` instead of `--column2`. Change the default to "count". Modify description to ".... with read count per reference, default ..."

2020-10-23 01:09 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser.add_argument("-g","--column3", default= "sample", help = "Header of fourth output column wih name of sample library, default : sample")
Rename to `--opt-col-name`. Make this an optional field. If the option is not given then the column will not print in the output. Change description to "Optional name for 3rd column (column won't be printed if empty)". Note that there is no default.

2020-10-23 01:09 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser.add_argument("-l", "--library_name", default= "sample name", help = "Name of library(sample) that will be used as fouth column name")
Rename to `--opt-col-val`. Fix description accordingly.

2020-10-23 01:09 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser.add_argument("-s","--col_delimiter", default= "\t", help = "Delimiter to seperate the columns of the output file, default : tab(\t)")
Rename to `--delim`. Modify description "..., default: TAB". Note the the "\t" was actually printed as a literal tab character in the help message (see file above).

2020-10-23 01:09 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser.add_argument("-o", "--ofile", help = "Column wise output file with Tab seperated output filename of your choice")
Change description to "Name of delimited 2-/3-column output file". File is not necessarily Tab delimited.

2020-10-23 01:09 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +if args.fileformat == "sam":
The option `--fileformat` asks for "sam" or "bam" but "bam" is never checked here. If "bam" is the default then rename the option to `--sam` and make it boolean. If the option is provided the script will read sam, otherwise, it will read bam.

2020-10-23 01:09 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +#bamfile = pysam.AlignmentFile(args.ifile, "r", check_sq=False)
Delete

2020-10-23 01:09 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +    reference_counts[reference] +=  [query_length]
```suggestion
    if reference not in reference_counts:
        reference_counts[reference] =  0
    reference_counts[reference] +=  1
```

2020-10-23 01:09 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +        f.write(reference + delim + str(len(count)) + delim + args.library_name + "\n")
```suggestion
        f.write(reference + delim + str(count) + delim + args.library_name + "\n")
```

2020-11-04 23:56 UTC, dar19 commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser = argparse.ArgumentParser()
Description added.

2020-11-04 23:58 UTC, dar19 commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser.add_argument("-c","--column1", default= "reference", help = "Header of first output column wih reference names, default: reference")
done.

2020-11-04 23:58 UTC, dar19 commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser.add_argument("-d","--column2", default= "read_count", help = "Header of second output column wih No of counts per reference, default : count")
done.

2020-11-05 14:47 UTC, dar19 commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser.add_argument("-g","--column3", default= "sample", help = "Header of fourth output column wih name of sample library, default : sample")
done

2020-11-05 22:11 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser = argparse.ArgumentParser(description='Count reads from sam/bam file')
'Count reads aligned on each reference sequence in a SAM/BAM file'

2020-11-05 22:11 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser.add_argument("-c", "--ref-col-name", default="reference", help="Header of column wih references, default: reference")
"Name of output column with reference sequence ids"

2020-11-05 22:11 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser.add_argument("-d", "--cnt-col-name", default="count", help="Header of column with read count per reference, default")
"Name of output columns with read count"

Also the description is missing the default.

2020-11-05 22:11 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser.add_argument("-g", "--opt-col-name", help="Header of optional column for sample/library name")
"Name of an optional column e.g. sample_name"

2020-11-05 22:11 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser.add_argument("-l", "--opt-col-val", help="Value of optional column for sample/library name")
"Value for the optional column; same for all rows"

2020-11-05 22:11 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser.add_argument("-o", "--ofile", help="Column wise output file with Tab seperated output filename of your choice")
"Columnar output file with read count per reference"

2020-11-05 22:11 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +    print(delim.join([args.ref_col_name, args.cnt_col_name]) + "\n")
Consider using the following for cleaner code.
```python
header = [args.ref_col_name, args.cnt_col_name]
if args.opt_col_name and args.opt_col_val:
    header += [args.opt_col_name]
print(delim.join(header) + "\n")
```

2020-11-05 22:11 UTC, mnsmar commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +        print(reference + delim + str(count) + "\n")
```python
row = [reference, str(count)] 
if args.opt_col_name and args.opt_col_val:
        row += args.opt_col_val
print(delim.join(row) + "\n")
```

2020-11-09 16:31 UTC, mnsmar commented on sam-per-ref-count/README.md
> +
This needs to be updated to reflect the options changes

2020-11-10 03:14 UTC, dar19 reviewed
updated with all required changes

2020-11-10 03:14 UTC, dar19 commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser.add_argument("-l", "--library_name", default= "sample name", help = "Name of library(sample) that will be used as fouth column name")
done

2020-11-10 03:14 UTC, dar19 commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser.add_argument("-s","--col_delimiter", default= "\t", help = "Delimiter to seperate the columns of the output file, default : tab(\t)")
done

2020-11-10 03:14 UTC, dar19 commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +parser.add_argument("-o", "--ofile", help = "Column wise output file with Tab seperated output filename of your choice")
done

2020-11-10 03:14 UTC, dar19 commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +#bamfile = pysam.AlignmentFile(args.ifile, "r", check_sq=False)
done.

2020-11-10 03:14 UTC, dar19 commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +    reference_counts[reference] +=  [query_length]
done

2020-11-10 03:14 UTC, dar19 commented on sam-per-ref-count/bin/sam-per-ref-count.py
> +        f.write(reference + delim + str(len(count)) + delim + args.library_name + "\n")
removed output option into file, we can directly save it from terminal to file.

2020-11-10 03:15 UTC, dar19 commented
All changes made and updated

2020-11-10 03:29 UTC, merged